rethinkdb:
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  image: gerencio/rethinkdb
  volumes: 
  - ${data}:/data
